# my global config
global:
  scrape_interval:     1s
  evaluation_interval: 1s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'my-project'
rule_files:
  - "/etc/prometheus-rules/*.rules"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1s
    static_configs:
         - targets: ['localhost:9090']
  - job_name: 'delorean'
    scrape_interval: 1s
    metrics_path: '/travel-back/prometheus'
    static_configs:
         - targets: ['delorean:8080']

